sudo: false
language: ruby
rvm:
  - 2.2
  - 2.6
  - 2.7
services:
  - mysql
addons:
  postgresql: "9.6"
env:
  global:
    - CC_TEST_REPORTER_ID=12e1facab2e8910c9b9d6b9e6870c5544a5c44a1bef25cc6638fd132aa4af6b4
  matrix:
    - DB=mysql
    - DB=pg
gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile
matrix:
  include:
    - env: DB=makara_mysql
      gemfile: gemfiles/6.0.gemfile
      rvm: 2.6
    - env: DB=makara_pg
      gemfile: gemfiles/6.0.gemfile
      rvm: 2.6
    - env: DB=makara_mysql
      gemfile: gemfiles/6.0.gemfile
      rvm: 2.7
    - env: DB=makara_pg
      gemfile: gemfiles/6.0.gemfile
      rvm: 2.7
  exclude:
    - gemfile: gemfiles/3.2.gemfile
      rvm: 2.6
    - gemfile: gemfiles/3.2.gemfile
      rvm: 2.7
    - gemfile: gemfiles/4.2.gemfile
      rvm: 2.7
    - gemfile: gemfiles/6.0.gemfile
      rvm: 2.2
before_install:
  - if [`ruby -e 'exit(RUBY_VERSION.to_f < 2.7)'`]; then
      gem i rubygems-update -v '< 3' && update_rubygems;
      gem install bundler -v '< 2';
    fi
  - gem --version
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_script:
  - mysql -V
  - mysql -u root -e 'CREATE DATABASE travis_ci_test;'
  - psql -c "SELECT version();"
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

